CUDA_VISIBLE_DEVICES=0 python3 -m classifier train-classifier configs/train_classifier_ae_ld32.py -g 0 -C "clr_ae_ld32_v1"
CUDA_VISIBLE_DEVICES=0 python3 -m classifier train-classifier configs/train_classifier_ae_ld64.py -g 0 -C "clr_ae_ld64_v1"
CUDA_VISIBLE_DEVICES=0 python3 -m classifier train-classifier configs/train_classifier_ae_ld128.py -g 0 -C "clr_ae_ld128_v1"
CUDA_VISIBLE_DEVICES=0 python3 -m classifier train-classifier configs/train_classifier_ae_ld256.py -g 0 -C "clr_ae_ld256_v1"
CUDA_VISIBLE_DEVICES=0 python3 -m classifier train-classifier configs/train_classifier_vae_ld32.py -g 0 -C "clr_vae_ld32_v1"
CUDA_VISIBLE_DEVICES=0 python3 -m classifier train-classifier configs/train_classifier_vae_ld64.py -g 0 -C "clr_vae_ld64_v1"
CUDA_VISIBLE_DEVICES=0 python3 -m classifier train-classifier configs/train_classifier_vae_ld128.py -g 0 -C "clr_vae_ld128_v1"
CUDA_VISIBLE_DEVICES=0 python3 -m classifier train-classifier configs/train_classifier_vae_ld256.py -g 0 -C "clr_vae_ld256_v1"